[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
serde_json = "1.0.80"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 0